### ISSUE TITLE
Shops and Book and Quill

### ISSUE THREAD

**Issue by Deffohn** [Caltinor/DiceMC-Money-Mod#16]
Hello,

`[23:04:22] [Server thread/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128456_()" because "nbt" is null
	Index: 4
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		2: ASM: class net.mehvahdjukaar.supplementaries.common.events.ServerEvents onRightClickBlockHigh(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		3: NORMAL
		4: ASM: class dicemc.money.event.EventHandler onSignRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		5: ASM: class dicemc.money.event.EventHandler onStorageOpen(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		6: net.minecraftforge.eventbus.EventBus$$Lambda$3758/0x000000080159e6f0@f9c8c69
		7: ASM: class lilypuree.decorative_blocks.events.CallBacks onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		8: ASM: class com.simibubi.create.foundation.tileEntity.behaviour.linked.LinkHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		9: ASM: class com.simibubi.create.foundation.tileEntity.behaviour.filtering.FilteringHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		10: ASM: class com.simibubi.create.foundation.tileEntity.behaviour.edgeInteraction.EdgeInteractionHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		11: ASM: class com.simibubi.create.foundation.block.ItemUseOverrides onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		12: ASM: class com.simibubi.create.content.logistics.block.funnel.FunnelItem funnelItemAlwaysPlacesWhenUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		13: ASM: class com.simibubi.create.content.contraptions.components.flywheel.engine.FurnaceEngineBlock usingFurnaceEngineOnFurnacePreventsGUI(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		14: LOW
		15: ASM: class net.mehvahdjukaar.supplementaries.common.events.ServerEvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		16: LOWEST
		17: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem consumeDurabilityOnPlace(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128456_()" because "nbt" is null
	at TRANSFORMER/dicemcmm@1.18.1-2.0.13/dicemc.money.event.EventHandler.getItemFromBook(EventHandler.java:272)
	at TRANSFORMER/dicemcmm@1.18.1-2.0.13/dicemc.money.event.EventHandler.lambda$activateShop$1(EventHandler.java:247)
	at TRANSFORMER/forge@39.0.59/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:164)
	at TRANSFORMER/dicemcmm@1.18.1-2.0.13/dicemc.money.event.EventHandler.activateShop(EventHandler.java:242)
	at TRANSFORMER/dicemcmm@1.18.1-2.0.13/dicemc.money.event.EventHandler.onSignRightClick(EventHandler.java:182)
	at net.minecraftforge.eventbus.ASMEventHandler_38_EventHandler_onSignRightClick_RightClickBlock.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@39.0.59/net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:757)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:315)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

[23:04:22] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128456_()" because "nbt" is null
	at dicemc.money.event.EventHandler.getItemFromBook(EventHandler.java:272) ~[DiceMC%20Money-1.18.1-2.0.13.jar%2354!/:1.18.1-2.0.13]
	at dicemc.money.event.EventHandler.lambda$activateShop$1(EventHandler.java:247) ~[DiceMC%20Money-1.18.1-2.0.13.jar%2354!/:1.18.1-2.0.13]
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:164) ~[forge-1.18.1-39.0.59-universal.jar%2383!/:?]
	at dicemc.money.event.EventHandler.activateShop(EventHandler.java:242) ~[DiceMC%20Money-1.18.1-2.0.13.jar%2354!/:1.18.1-2.0.13]
	at dicemc.money.event.EventHandler.onSignRightClick(EventHandler.java:182) ~[DiceMC%20Money-1.18.1-2.0.13.jar%2354!/:1.18.1-2.0.13]
	at net.minecraftforge.eventbus.ASMEventHandler_38_EventHandler_onSignRightClick_RightClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:757) ~[forge-1.18.1-39.0.59-universal.jar%2383!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:315) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2379!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

I notice to you a bug on server at least : can't setup a shop with book and quill and getting this crash (do not shutdown the server) on setuping the shop. On the picture I show the raw book and quill in the storage of the shop before setup, and the sign shop after I right clicked twice (with empty hand for sure) on it

![book and quill shop](https://user-images.githubusercontent.com/50484560/151453077-a349c68c-e68e-4668-b64b-3c38355ba880.jpg)

Have a nice day !

**Comment by Caltinor** [comment]
Thank you.  this is a pretty obvious error.  I will have an update shortly.

**Comment by Caltinor** [comment]
Resolved in this release
https://www.curseforge.com/minecraft/mc-mods/dicemc-money-mod/files/3626159
