### ISSUE TITLE
[Bug] SQL Database cannot connect

### ISSUE THREAD

**Issue by JustAnotherGhostName** [Caltinor/DiceMC-Money-Mod#38]
When enabling history as part of the `enable_history` config option in the server settings, the chest shops on the server no longer works. When you right click the chest shop, the following error is recorded in the server logs. See attached.

[message (9).txt](https://github.com/Caltinor/DiceMC-Money-Mod/files/10430464/message.9.txt)

I am guessing it has to do with connecting to an SQL database due to the following lines:
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because "this.con" is null
    at TRANSFORMER/dicemcmm@1.19.2-0.0.2/dicemc.money.storage.DatabaseManager.postEntry(DatabaseManager.java:53)
    at TRANSFORMER/dicemcmm@1.19.2-0.0.2/dicemc.money.event.EventHandler.processTransaction(EventHandler.java:388)
    at TRANSFORMER/dicemcmm@1.19.2-0.0.2/dicemc.money.event.EventHandler.onSignRightClick(EventHandler.java:184)
    at TRANSFORMER/dicemcmm@1.19.2-0.0.2/dicemc.money.event.__EventHandler_onSignRightClick_RightClickBlock.invoke(.dynamic)
    
I am unfamiliar with Dbeaver and H2 Database systems, however, I am assuming I dont need to install and setup a MySQL database on the server as the config does not have any options regarding signing in and the port.

**Comment by Caltinor** [comment]
The history feature was never fully implemented. It's been on my to-do for a long time now.
